import jsPDF from 'jspdf';

interface ExportMessage {
  text: string;
  isBot: boolean;
}

export function exportChatToPdf({
  title,
  messages,
  filename,
}: {
  title: string;
  messages: ExportMessage[];
  filename?: string;
}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPageIfNeeded = (requiredSpace: number) => {
    if (y + requiredSpace > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Header
  doc.setFillColor(15, 76, 92); // deep teal
  doc.rect(0, 0, pageWidth, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 18);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Oceanopedia Research Report — ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, 28);

  y = 45;
  doc.setTextColor(60, 60, 60);

  // Filter out welcome message (first bot message)
  const chatMessages = messages.slice(1);

  if (chatMessages.length === 0) {
    doc.setFontSize(11);
    doc.text('No analyses to export yet. Run a query first.', margin, y);
    doc.save(filename || `${title.toLowerCase().replace(/\s+/g, '-')}-report.pdf`);
    return;
  }

  chatMessages.forEach((msg) => {
    const label = msg.isBot ? 'AI Analysis' : 'Query';
    const labelColor: [number, number, number] = msg.isBot ? [15, 76, 92] : [80, 80, 80];

    // Label
    addPageIfNeeded(12);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...labelColor);
    doc.text(label, margin, y);
    y += 5;

    // Strip markdown for clean PDF text
    const cleanText = msg.text
      .replace(/#{1,6}\s?/g, '')
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/`{1,3}[^`]*`{1,3}/g, (m) => m.replace(/`/g, ''))
      .replace(/\|/g, ' ')
      .replace(/---+/g, '')
      .replace(/\n{3,}/g, '\n\n');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);

    const lines = doc.splitTextToSize(cleanText, contentWidth);
    const lineHeight = 4.5;

    for (const line of lines) {
      addPageIfNeeded(lineHeight + 2);
      doc.text(line, margin, y);
      y += lineHeight;
    }

    // Separator
    y += 4;
    addPageIfNeeded(4);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  });

  // Footer on last page
  const footerY = pageHeight - 10;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Oceanopedia — AI-Driven Ocean Insights', margin, footerY);
  doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - margin - 15, footerY);

  doc.save(filename || `${title.toLowerCase().replace(/\s+/g, '-')}-report.pdf`);
}
